### ISSUE TITLE
publish cookbook to supermarket

### ISSUE THREAD

**Issue by vkhatri** [Icinga/chef-icinga2repo#1]
Required actions.
- Publish cookbook to Chef supermarket
- Add Chef Supermarket user `vkhatri` as a collaborator

**Comment by vkhatri** [comment]
@dnsmichi ping!

**Comment by dnsmichi** [comment]
@vkhatri please get in touch with @bobapple who's managing the infrastructure and accounts. Thanks.

**Comment by bobapple** [comment]
@vkhatri I uploaded the cookbook and added you as collaborator
